name: WebVTT Cue Settings
description: The members of the `VTTCue` API can be used to update cues dynamically.
spec: https://w3c.github.io/webvtt/#the-vttcue-interface
compat_features:
  - api.VTTCue.align
  - api.VTTCue.line
  - api.VTTCue.position
  - api.VTTCue.size
  - api.VTTCue.snapToLines
  - api.VTTCue.vertical
